project_id = "reztyrrafsmlvvlqvsqt"

[functions.notification-worker]
verify_jwt = false

[functions.floq-mention-handler]
verify_jwt = false

[functions.upsert-presence]
verify_jwt = true

[functions.activity-score-processor]
verify_jwt = false

[functions.boost-analytics]
verify_jwt = true

[functions.manage-participant-role]
verify_jwt = true

[functions.plan-rsvp]
verify_jwt = true

[functions.update-floq-settings]
verify_jwt = true

[functions.get_hotspots]
verify_jwt = true

[functions.generate-afterglow-summary]
verify_jwt = true

[functions.create-share-link]
verify_jwt = true

[functions.render-og-card]
verify_jwt = false

[functions.submit-plan-vote]
verify_jwt = true

[functions.suggest-venues]
verify_jwt = true

[functions.finalize-plan]
verify_jwt = true

[functions.invite-external-friends]
verify_jwt = true

[functions.sync-plan-changes]
verify_jwt = true

[functions.parse-voice-to-stop]
verify_jwt = true

[functions.post-floq-message]
verify_jwt = true