project_id = "reztyrrafsmlvvlqvsqt"

[functions.notification-worker]
verify_jwt = false

[functions.floq-mention-handler]
verify_jwt = false

[functions.upsert-presence]
verify_jwt = true

[functions.activity-score-processor]
verify_jwt = false

[functions.boost-analytics]
verify_jwt = true

[functions.manage-participant-role]
verify_jwt = true

[functions.plan-rsvp]
verify_jwt = true

[functions.update-floq-settings]
verify_jwt = true

[functions.get_hotspots]
verify_jwt = true