// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/integrations/supabase/types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://reztyrrafsmlvvlqvsqt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJlenR5cnJhZnNtbHZ2bHF2c3F0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNTI5MTcsImV4cCI6MjA2NzYyODkxN30.6rCBIkV5Fk4qzSfiAR0I8biCQ-YdfdT-ZnJZigWqSck";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create the main client with v2 configuration
const baseClient = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    headers: { 
      'X-Client-Info': 'floq-web v1.0',
      'Accept-Profile': 'public',
      'Range-Unit': 'items'
    },
  },
  db: {
    schema: 'public',
    fetchOptions: { 
      // ✅ Skip HEAD requests to prevent 400 errors from PostgREST
      noHead: true 
    } as any,
  },
});

// Export the properly typed v2 client
export const supabase = baseClient;