// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/integrations/supabase/types';

export const SUPABASE_URL = 'https://reztyrrafsmlvvlqvsqt.supabase.co';
export const SUPABASE_PUBLISHABLE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJlenR5cnJhZnNtbHZ2bHF2c3F0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNTI5MTcsImV4cCI6MjA2NzYyODkxN30.6rCBIkV5Fk4qzSfiAR0I8biCQ-YdfdT-ZnJZigWqSck';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create the main client with v2 configuration
const resolvedUrl = SUPABASE_URL || 'https://reztyrrafsmlvvlqvsqt.supabase.co';
const resolvedKey = SUPABASE_PUBLISHABLE_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJlenR5cnJhZnNtbHZ2bHF2c3F0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNTI5MTcsImV4cCI6MjA2NzYyODkxN30.6rCBIkV5Fk4qzSfiAR0I8biCQ-YdfdT-ZnJZigWqSck';

if (!resolvedUrl || !resolvedKey) {
  console.error('[Supabase] Missing configuration:', { resolvedUrl, hasKey: !!resolvedKey });
}

const baseClient = createClient<Database>(resolvedUrl, resolvedKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    headers: { 
      'X-Client-Info': 'floq-web v1.0',
      'Accept-Profile': 'public',
      'Range-Unit': 'items'
    },
  },
  db: {
    schema: 'public',
  },
});

// Export the properly typed v2 client
export const supabase = baseClient;