// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { StorageClient } from '@supabase/storage-js';
import type { Database } from '@/types/database';

const SUPABASE_URL = "https://reztyrrafsmlvvlqvsqt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJlenR5cnJhZnNtbHZ2bHF2c3F0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNTI5MTcsImV4cCI6MjA2NzYyODkxN30.6rCBIkV5Fk4qzSfiAR0I8biCQ-YdfdT-ZnJZigWqSck";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Custom StorageClient to silence pre-warm warnings in production
class QuietStorageClient extends StorageClient {
  // @ts-ignore - Override private method to suppress pre-warm logs
  private prewarmUrl(url: string) {
    // Only allow pre-warming in development mode
    if (import.meta.env.MODE === 'development') {
      return super['prewarmUrl']?.(url);
    }
    // Silently skip pre-warming in production/preview
  }
}

// Create the main client with v2 configuration
const baseClient = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    headers: { 'X-Client-Info': 'floq-web v1.0' },
  },
});

// Export the properly typed v2 client
export const supabase = baseClient;